name: CI/CD workflow

on:
  workflow_dispatch:
    inputs:
      steps:
        description: "Steps to run"
        required: true
        type: choice
        options:
          - integration
          - all
        default: all

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sentiment-app-onnx
  S3_BUCKET: mlops-lab11-models-pjarosz

jobs:
  integration:
    if: ${{ inputs.steps == 'all' || inputs.steps == 'integration' }}
    name: checks_and_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group integration

      - name: Run Ruff check
        run: uv run ruff check .

      - name: Run Pytest
        run: uv run pytest

  deployment:
    needs: [integration]
    if: ${{ inputs.steps == 'all' && needs.integration.result == 'success' }}
    name: run_scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --group deployment

      - name: Download artifacts from S3
        run: uv run python scripts/main.py --download

      - name: Export model to ONNX
        run: uv run python scripts/main.py --export

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Build and Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Delete stack if in rollback state
        run: |
          STATUS=$(aws cloudformation describe-stacks \
            --stack-name sentiment-app-stack \
            --region ${{ env.AWS_REGION }} \
            --query 'Stacks[0].StackStatus' \
            --output text 2>/dev/null || echo "NOT_FOUND")

          echo "Current stack status: $STATUS"

          case "$STATUS" in
            *ROLLBACK* )
              aws cloudformation delete-stack --stack-name sentiment-app-stack --region ${{ env.AWS_REGION }}
              aws cloudformation wait stack-delete-complete --stack-name sentiment-app-stack --region ${{ env.AWS_REGION }}
              ;;
          esac

      - name: Deploy with AWS SAM
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sam deploy \
            --template-file sam-template.yaml \
            --stack-name sentiment-app-stack \
            --image-repository $REGISTRY/$REPOSITORY \
            --parameter-overrides \
              ImageUri=$REGISTRY/$REPOSITORY:$IMAGE_TAG \
              LambdaExecutionRoleArn=${{ secrets.LAMBDA_ROLE_ARN }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --region ${{ env.AWS_REGION }}
